ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'RECEIVED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'PARSED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'MATCHED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'PRICED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'QUOTE_READY';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'NEEDS_CLARIFICATION';

ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "threadId" TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS "Rfq_workspaceId_threadId_idx" ON "Rfq"("workspaceId", "threadId");
