ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'PARSING';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'MATCHING';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'SENDING';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'NEEDS_CLARIFICATION';

ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "lastError" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "requirementsHash" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "quoteBlockedReason" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "strictness" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "lastMatchedAt" TIMESTAMP(3);
ALTER TABLE "Rfq" ADD COLUMN IF NOT EXISTS "lastPricedAt" TIMESTAMP(3);

CREATE TABLE IF NOT EXISTS "RfqEvent" (
  "id" TEXT NOT NULL,
  "workspaceId" TEXT NOT NULL,
  "rfqId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT '',
  "reason" TEXT NOT NULL DEFAULT '',
  "gmailMessageId" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RfqEvent_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "RfqEvent_rfqId_createdAt_idx" ON "RfqEvent"("rfqId", "createdAt");
ALTER TABLE "RfqEvent" DROP CONSTRAINT IF EXISTS "RfqEvent_rfqId_fkey";
ALTER TABLE "RfqEvent" ADD CONSTRAINT "RfqEvent_rfqId_fkey" FOREIGN KEY ("rfqId") REFERENCES "Rfq"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "RfqOutboundKey" (
  "id" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "rfqId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RfqOutboundKey_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "RfqOutboundKey_key_key" ON "RfqOutboundKey"("key");
CREATE INDEX IF NOT EXISTS "RfqOutboundKey_rfqId_idx" ON "RfqOutboundKey"("rfqId");
ALTER TABLE "RfqOutboundKey" DROP CONSTRAINT IF EXISTS "RfqOutboundKey_rfqId_fkey";
ALTER TABLE "RfqOutboundKey" ADD CONSTRAINT "RfqOutboundKey_rfqId_fkey" FOREIGN KEY ("rfqId") REFERENCES "Rfq"("id") ON DELETE CASCADE ON UPDATE CASCADE;
