ALTER TABLE "Workspace" ADD COLUMN "quoteSettings" JSONB;

ALTER TABLE "Quote" ADD COLUMN "documentMode" TEXT NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "Quote" ADD COLUMN "exportQuote" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Quote" ADD COLUMN "references" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "pdf" BYTEA;
ALTER TABLE "Quote" ADD COLUMN "pdfFilename" TEXT NOT NULL DEFAULT '';

ALTER TABLE "QuoteLine" ADD COLUMN "sku" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuoteLine" ADD COLUMN "modelName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuoteLine" ADD COLUMN "manufacturerPartNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuoteLine" ADD COLUMN "availability" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuoteLine" ADD COLUMN "leadTime" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuoteLine" ADD COLUMN "warranty" TEXT NOT NULL DEFAULT '';
ALTER TABLE "QuoteLine" ADD COLUMN "requirementText" TEXT NOT NULL DEFAULT '';
